{
    "__collections__":{
    "bestseller":[
     {
      "itemId": 355855624,
      "title": "만일 내가 인생을 다시 산다면(10만 부 기념 스페셜 에디션)",
      "description": "“하나의 문이 닫히면 또 하나의 문이 열린다. \n그러니 더 이상 고민하지 말고 그냥 재미있게 살아라!”\n\n30년 동안 정신분석 전문의로 일해 온 김혜남이 벌써 마흔이 된 당신에게 해 주고 싶은 말들을 담은 책이다. 그녀는 지금껏 살면서 한 가지 후회하는 게 있다면 스스로를 너무 닦달하며 인생을 숙제처럼 산 것이라고 말한다. 의사로, 엄마로, 아내로, 며느리로, 딸로 살면서 늘 의무와 책임감에 치여 어떻게든 그 모든 역할을 잘해 내려 애썼고 그러다 보니 정작 누려야 할 삶의 즐거움들을 놓쳐 버렸다는 것이다. 그러다 22년 전 마흔세 살에 파킨슨병 진단을 받으며 비로소 알게 되었다. 자신이 없으면 집안도 병원도 제대로 안 굴러갈 것 같았는데 세상은 너무나 멀쩡히 잘 굴러갔다. 그제야 그녀는 자신의 곁을 지켜 주...",
      "priceSales": 15480,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/5\/6\/2\/4\/355855624h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/5\/6\/2\/4\/355855624s.jpg",
      "categoryId": "119",
      "categoryName": "국내도서",
      "publisher": "메이븐",
      "author": "김혜남",
      "isbn": "9791190538510",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355855624&amp;refererType=8305",
      "rank": 1
     },
     {
      "itemId": 355430361,
      "title": "트렌드 코리아 2023",
      "description": "침체와 불황을 넘어 더 높이 뛰어오를 토끼의 해\n2023, 남다른 치열함과 기민함으로 새롭게 무장하라\n\n2년이 넘는 시간 동안 지속된 코로나19 사태를 거치면서 우리의 삶은 큰 변화를 맞이했다. 2022년 하반기에 이르러 사회적 거리두기가 해제되면서 한산했던 거리가 조금씩 활기를 띠기 시작했고 그곳을 오가는 사람들의 표정 역시 부쩍 밝아졌지만, 코로나19 이전의 풍경과 완전히 같을 수는 없었다. 그렇다면 우리는 무엇을 무기로 삼아 변화로 가득한 세상을 헤쳐나갈 것인가? 누구보다 촉각을 곤두세운 채 기민하게 움직이는 토끼의 기지가 필요한 2023년, 『트렌드 코리아 2023』은 남다른 치열함으로 무장하고 불황을 넘어 뛰어오르는 도약의 출발점이 될 것이다.",
      "priceSales": 17100,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/0\/3\/6\/1\/355430361h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/0\/3\/6\/1\/355430361s.jpg",
      "categoryId": "117",
      "categoryName": "국내도서",
      "publisher": "미래의창",
      "author": "김난도(金蘭都),전미영,최지혜,이수진,권정윤",
      "isbn": "9788959897094",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355430361&amp;refererType=8305",
      "rank": 2
     },
     {
      "itemId": 355978842,
      "title": "흔한남매 12",
      "description": "개성 만점 으뜸이 채널, 공포의 버스 안내 방송, 떡볶이 뷔페에 간 흔한남매, 으뜸이의 최악의 생일 파티, 상상 속 방학과 현실 속 방학의 차이, 엄지의 비밀 일상 등 흔한남매의 일상 속엔 생기 넘치는 공감과 웃음이 가득하다.‘흔한남매’는 유튜브 구독자 수가 243만 명, 누적 조회 수가 27억 회를 넘어서는 인기 크리에이터로, 흔한컴퍼니에 소속되어 있다. 상황극콩트 등을 통해 어린이들에게 큰 사랑을 받고 있으며, 주로 남매 사이에서 일어날 수 있는 현실적인 에피소드를 코믹하게 그려 내어 웃음과 공감을 이끌어 내고 있다.",
      "priceSales": 13050,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/8\/8\/4\/2\/355978842h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/8\/8\/4\/2\/355978842s.jpg",
      "categoryId": "110",
      "categoryName": "국내도서",
      "publisher": "미래엔아이세움",
      "author": "백난도,흔한남매,백난도",
      "isbn": "9791168414471",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355978842&amp;refererType=8305",
      "rank": 3
     },
     {
      "itemId": 355179957,
      "title": "아버지의 해방일지",
      "description": "새삼스럽게 경탄스럽다!\n압도적인 몰입감, 가슴 먹먹한 감동\n정지아의 손끝에서 펼쳐지는 시대의 온기\n\n미스터리 같은 한 남자가 헤쳐온 역사의 격랑\n그 안에서 발견하는 끝끝내 강인한 우리의 인생\n\n김유정문학상 심훈문학대상 이효석문학상 등을 수상하며 문학성을 두루 입증받은 ‘리얼리스트’ 정지아가 무려 32년 만에 장편소설을 발표했다. 써내는 작품마다 삶의 현존을 정확하게 묘사하며 독자와 평단의 찬사를 받아온 작가는 이번에 역사의 상흔과 가족의 사랑을 엮어낸 대작을 선보임으로써 선 굵은 서사에 목마른 독자들에게 한모금 청량음료 같은 해갈을 선사한다. 탁월한 언어적 세공으로 “한국소설의 새로운 화법을 제시”(문학평론가 정홍수)하기를 거듭해온 정지아는 한 시대를 풍미한 『빨치산의 딸』(1990) 이래로 다시 초심으로 ...",
      "priceSales": 13500,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/9\/9\/5\/7\/355179957h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/9\/9\/5\/7\/355179957s.jpg",
      "categoryId": "101",
      "categoryName": "국내도서",
      "publisher": "창비",
      "author": "정지아(鄭智我)",
      "isbn": "9788936438838",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355179957&amp;refererType=8305",
      "rank": 4
     },
     {
      "itemId": 355003332,
      "title": "불편한 편의점 2(단풍 에디션)",
      "description": "70만 독자를 사로잡은 재미와 감동 『불편한 편의점』이 다시 열렸다!\n\n한층 진득해진 이야기와 궁금증 가득한 캐릭터\n고난의 시간을 통과하는 사람들이 다시 편의점에 모여든다!\n\n출간 후 1년이 넘도록 독자의 사랑을 받으며 베스트셀러 상위권을 지키고 있는 소설, 김호연 작가의 『불편한 편의점』이 그 두 번째 이야기로 다시 찾아왔다. 서울역 노숙인 독고 씨가 편의점의 야간 알바로 일하면서 시작되는 1편의 이야기는 예측불허의 웃음과 따스한 온기로 잔잔한 감동을 선사했다. 『불편한 편의점 2』는 전편의 위트와 속 깊은 시선을 이어가며 더욱 진득한 이야기로 독자를 끌어당긴다. \n\n소설은 1편의 시간으로부터 1년 반이 흐른 여름날의 편의점을 스케치하며 시작된다. 그동안 세상도 달라지고 청파동의 ALWAYS편의점도 이모저...",
      "priceSales": 12600,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/3\/3\/3\/2\/355003332h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/3\/3\/3\/2\/355003332s.jpg",
      "categoryId": "101",
      "categoryName": "국내도서",
      "publisher": "나무옆의자",
      "author": "김호연",
      "isbn": "9791161571379",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355003332&amp;refererType=8305",
      "rank": 5
     },
     {
      "itemId": 348921505,
      "title": "불편한 편의점(40만부 기념 벚꽃 에디션)",
      "description": "※ 인터넷 한정 특별판: 매장 구매, 바로드림 구매 시에는 다른 표지의 에디션으로 제공됩니다.\n\n원 플러스 원의 기쁨, 삼각김밥 모양의 슬픔, 만 원에 네 번의 폭소가 터지는 곳!\n힘겨운 시대를 살아가는 우리들에게 다가온 조금 특별한 편의점 이야기\n\n누적 판매 40만부 돌파, 2022년 가장 사랑받는 소설\n★★★전 서점 종합베스트 1위, 2021 올해의 책,\n★★★국립중앙도서관 사서추천도서, 해외 6개국 판권 수출\n\n김호연 작가의 장편소설 『불편한 편의점』이 누적 판매 40만부 돌파를 기념하여 벚꽃 에디션으로 새 단장 했습니다. 2021년 4월에 출간되어 전 연령층의 폭넓은 공감을 얻으며 소설 읽기 바람을 일으킨 『불편한 편의점』의 열기는 지금도 현재진행형입니다. “읽는 내내 마음이 따뜻하고 먹먹했다” “눈...",
      "priceSales": 12600,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/1\/5\/0\/5\/348921505h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/1\/5\/0\/5\/348921505s.jpg",
      "categoryId": "101",
      "categoryName": "국내도서",
      "publisher": "나무옆의자",
      "author": "김호연",
      "isbn": "9791161571188",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=348921505&amp;refererType=8305",
      "rank": 6
     },
     {
      "itemId": 355900503,
      "title": "조국의 법고전 산책",
      "description": "쓰러지지 않고 세상 속을 걸어가는 사유와 성찰《사회계약론》부터 《영구 평화론》까지법학자 조국이 선택한 열다섯 권의 고전과 그 사상가들을 만나다《조국의 법고전 산책》은 저자 조국이 고른 법과 관련된 고전 15권을 중심으로 핵심 내용을 소개하고, 그것이 지금의 한국 사회에 어떤 의미를 갖는지 밝히는 책이다. 이 책에서 다루고 있는 법고전의 사상은 현대 민주주의 사회의 법과 제도 속에 여전히 살아 움직이고 있다.저자는 법고전의 보석 같은 문장을 뽑아내고 숨은 의미를 새롭게 발견하면서 이를 한국 사회에 적용해보자고 말한다. 자유, 평등, 법치, 사회계약, 평화, 소수자 보호, 시민불복종, 저항권, 죄형법정주의, 사법심사 등 법학의 핵심 개념을 통해 한국 사회의 법과 정의가 무엇인지 다시 돌아본다.어려운 고전을 다루...",
      "priceSales": 19800,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/0\/5\/0\/3\/355900503h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/0\/5\/0\/3\/355900503s.jpg",
      "categoryId": "119",
      "categoryName": "국내도서",
      "publisher": "오마이북",
      "author": "조국",
      "isbn": "9788997780518",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355900503&amp;refererType=8305",
      "rank": 7
     },
     {
      "itemId": 355002881,
      "title": "하얼빈",
      "description": "『칼의 노래』를 넘어서는 깊이와 감동\n김훈이 반드시 써내야만 했던 일생의 과업\n\n‘우리 시대 최고의 문장가’ ‘작가들의 작가’로 일컬어지는 소설가 김훈의 신작 장편소설 『하얼빈』이 출간되었다. 『하얼빈』은 김훈이 작가로 활동하는 내내 인생 과업으로 삼아왔던 특별한 작품이다. 작가는 청년 시절부터 안중근의 짧고 강렬했던 생애를 소설로 쓰려는 구상을 품고 있었고, 안중근의 움직임이 뿜어내는 에너지를 글로 감당하기 위해 오랜 시간을 들여 ‘인간 안중근’을 깊이 이해해나갔다. 그리고 2022년 여름, 치열하고 절박한 집필 끝에 드디어 그 결과물을 세상에 내놓게 되었다.\n\n 『하얼빈』에서는 단순하게 요약되기 쉬운 실존 인물의 삶을 역사적 기록보다도 철저한 상상으로 탄탄하게 재구성하는 김훈의 글쓰기 방식이 빛을 발한다...",
      "priceSales": 14400,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/2\/8\/8\/1\/355002881h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/2\/8\/8\/1\/355002881s.jpg",
      "categoryId": "101",
      "categoryName": "국내도서",
      "publisher": "문학동네",
      "author": "김훈(金薰)",
      "isbn": "9788954699914",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355002881&amp;refererType=8305",
      "rank": 8
     },
     {
      "itemId": 356007211,
      "title": "나는 논어를 만나 행복해졌다",
      "description": "★★★★★ \n4000만 독자가 믿고 따르는 독서회 리더,\n판덩이 설명하는 생활밀착형 논어\n인생에 한 번은 논어를 읽어야 한다\n★★★★★\n\n＂무엇을 해도 공허한 인생, 이제는 논어다!＂\n시대 불문의 고전, 논어로 느끼는 ‘배움의 매력’\n\n수천 년 전의 책이 여전히 사랑을 받고 있다면 이는 단 한 가지 이유다. 여전히 책의 가치가 그 시대에 추앙받고 있기 때문이다. 특히 삶이 버겁고 고통스러울 때 많은 사람은 멘토가 될만한 인물의 처세와 지혜를 찾는다. 세상은 급속도로 변화를 맞이하며 극도의 편리함과 편안함을 제공하고 있지만 내면은 여전히 공허하고 허탈하다. 이 어지러운 시대에 우리는 다시금 옛 위인의 지혜를 탐색하게 된다. 그리고 그 정수가 바로 『논어』이다. \n\n저자는 현재 4000만 명이 넘는 회원이 소속...",
      "priceSales": 16020,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/7\/2\/1\/1\/356007211h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/7\/2\/1\/1\/356007211s.jpg",
      "categoryId": "118",
      "categoryName": "국내도서",
      "publisher": "미디어숲",
      "author": "판덩(樊登)",
      "isbn": "9791158741716",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=356007211&amp;refererType=8305",
      "rank": 9
     },
     {
      "itemId": 356050447,
      "title": "설민석의 한국사 대모험 23",
      "description": "*누적 판매 500만 부 돌파!*초등학습만화 시리즈 베스트셀러!*현직 초등 교사의 강력 추천!우리 아이 한국사 첫걸음,〈설민석의 한국사 대모험〉으로 시작하세요!2017년 1권이 처음 출간된 이래, 누적 판매 부수 500만 부라는 경이적인 수치를 기록하며 대한민국 대표 어린이 역사책으로 굳건히 자리매김한 〈설민석의 한국사 대모험〉! 〈설민석의 한국사 대모험〉은 아이들이 처음 접하는 한국사를 재미있는 만화와 깊이 있는 부록으로 쉽고, 재미있고, 유익하게 전달합니다. 이 책은 우리 아이들이 놀이하듯 즐겁게 한국사를 접하며 한국사에 관심을 가지고, 나아가 한국사를 사랑하는 어린이로 성장하게 도와줄 것입니다. 〈설민석의 한국사 대모험〉 23권에서는 조선 인조 대에 일어난 병자호란을 재미있는 만화로 담아냈습니다. 병자...",
      "priceSales": 11700,
      "coverSmallUrl": "http:\/\/bimage.interpark.com\/goods_image\/0\/4\/4\/7\/356050447h.jpg",
      "coverLargeUrl": "http:\/\/bimage.interpark.com\/goods_image\/0\/4\/4\/7\/356050447s.jpg",
      "categoryId": "110",
      "categoryName": "국내도서",
      "publisher": "단꿈아이",
      "author": "설민석,스토리박스",
      "isbn": "9791191496642",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=356050447&amp;refererType=8305",
      "rank": 10
     },
     {
      "itemId": 355397254,
      "title": "이 책은 돈 버는 법에 관한 이야기",
      "description": "“10년간 꾸준히 유지해온 철학과 노하우라면\n돈을 주고라도 배워야 한다”\n\n★★★ 부읽남TV, 월급쟁이부자들TV, 스터디언 320만 채널 추천 ★★★\n★★★ 송은이, 홍석천, 이랑주 강력 추천 ★★★\n\n부읽남TV, 월급쟁이부자들TV, 스터디언 등 320만 채널이 추천하고 송은이, 홍석천, 이랑주가 “돈을 주고라도 배워야 한다”며 강력 추천하는 책. 10년간 꾸준히 연매출 10억 원 이상을 만드는 ‘골목 장사의 고수’이자, 장사-집필-강연-진행-공연 등으로 돈의 선순환을 만들어 ‘돈으로부터 해방된 자’ 고명환의 《이 책은 돈 버는 법에 관한 이야기》다.\n30여 년 전, MBC 공채 개그맨으로 일하며 월 3,000만 원을 벌던 시절도 있었지만 통장은 늘 텅 비어 있었고, 삶의 열정도 사라졌다. 그런 그의 인생을...",
      "priceSales": 15120,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/7\/2\/5\/4\/355397254h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/7\/2\/5\/4\/355397254s.jpg",
      "categoryId": "117",
      "categoryName": "국내도서",
      "publisher": "라곰",
      "author": "고명환",
      "isbn": "9791189686536",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355397254&amp;refererType=8305",
      "rank": 11
     },
     {
      "itemId": 354750490,
      "title": "역행자",
      "description": "“절대 읽지 마라! \n죽을 때까지 순리자로 살고 싶다면!” \n\n오타쿠 흙수저에서 \n월 1억 자동 수익을 실현한 무자본 연쇄창업마,\n라이프해커 자청의 인생 역주행 공식 대공개!\n\n대부분의 사람들은 유전자와 본성의 명령을 그대로 따르기 때문에 평범함을 벗어날 수 없다. 하지만 정작 자신은 이를 모른 채 ‘나는 달라’ 하는 자의식에 사로잡혀서 무한 합리화에 빠져 살아간다. 스스로가 얼마나 많은 정신적, 심리적 오류를 저지르는지 알지 못한 채 매일 똑같은 쳇바퀴를 돌 뿐이다. 왜 우리는 진짜 자유를 얻지 못하는가? 왜 늘 돈 이야기를 하면서도 평생 돈에 허덕이는가?\n\n 저자 역시 스무 살까지는 이런 쳇바퀴에 갇혀 있었기 때문에, 그 상황을 누구보다 잘 알았다.  자청의 첫 책 『역행자』에는 가난한 인생에서 벗어나 ...",
      "priceSales": 15750,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/0\/4\/9\/0\/354750490h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/0\/4\/9\/0\/354750490s.jpg",
      "categoryId": "117",
      "categoryName": "국내도서",
      "publisher": "웅진지식하우스",
      "author": "자청",
      "isbn": "9788901260716",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=354750490&amp;refererType=8305",
      "rank": 12
     },
     {
      "itemId": 355777159,
      "title": "이은경쌤의 초등어휘일력 365",
      "description": "『오즈의 마법사』와 『해리포터』에서『만복이네 떡집』과『불편한 편의점』까지15만 부모의 멘토, 이은경쌤이 초등 문학 속 어휘를 모두 모았습니다!유튜브 누적 조회수 1,300만 뷰, 네이버카페 유튜브 ‘슬기로운초등생활’ 15만 부모의 멘토이자 자녀교육 베스트셀러 저자인 이은경쌤이 엄마와 아이가 함께 보는 초등어휘일력을 출간했다. 탁상달력 형태인 이 책은 1월 1일부터 12월 31일까지 어린이가 좋아하는 문학 속 다양하고 흥미로운 어휘를 제공한다. 이은경 쌤 특유의 친근한 위로와 응원가가 매일매일 그날의 어휘에 맞게 담겨있어 해당 일력을 보는 아이와 부모의 마음을 따듯하게 어루만져줄 것이다.이은경 쌤이 이번 일력에 특히 신경 쓴 부분은, 아이들이 좋아할 만한 문학 작품들 속에서 어휘들을 선별했다는 것이다. 15년...",
      "priceSales": 16920,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/7\/1\/5\/9\/355777159h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/7\/1\/5\/9\/355777159s.jpg",
      "categoryId": "111",
      "categoryName": "국내도서",
      "publisher": "포레스트북스",
      "author": "이은경",
      "isbn": "9791192625300",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355777159&amp;refererType=8305",
      "rank": 13
     },
     {
      "itemId": 355979180,
      "title": "Go Go 카카오프렌즈 26: 폴란드",
      "description": "세계를 무대로 꿈꾸며 성장할 아이들에게 어린 시절의 다양한 경험은 꿈의 크기를 바꾸게 할 만큼 중요한 일이다. 이 시리즈는 세계로 나아가 꿈을 펼칠 아이들을 위해 기획된 ‘세계 역사 문화 체험 학습만화’로, 처음 세계를 접하는 아이들의 호기심을 자극할 만한 주제와 내용을 재미있는 스토리로 풀어내어 세계에 대한 관심을 높인다.카카오프렌즈가 역사 퍼즐을 찾아 떠난 스물여섯 번째 나라는 폴란드다. 북쪽으로 발트해를 끼고 여러 나라와 국경을 맞대고 있는 폴란드는 한마디로 유럽의 한가운데 있는 나라다. 폴란드로 시간여행을 떠난 카카오프렌즈는 유럽 대륙의 중심에서 어떤 역사와 문화를 체험했을까?7살에 작곡을 시작한 천재 음악가 쇼팽과 최초의 여성 노벨상 수상자 마리 퀴리가 태어난 도시 바르샤바. 폴란드의 수도이자 세계...",
      "priceSales": 13320,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/9\/1\/8\/0\/355979180h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/9\/1\/8\/0\/355979180s.jpg",
      "categoryId": "110",
      "categoryName": "국내도서",
      "publisher": "아울북",
      "author": "김정한,김미영",
      "isbn": "9788950941901",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355979180&amp;refererType=8305",
      "rank": 14
     },
     {
      "itemId": 355138911,
      "title": "마흔에 읽는 니체",
      "description": "내일 죽을 것처럼 오늘을 사랑하라!\n마흔의 삶에 자극제가 되는 니체의 25가지 조언\n\n마흔, 인생의 중반에서 후반으로 넘어가는 과도기의 나이다. 사십 대에는 안정적인 삶을 살 줄 알았지만 여전히 불안정하다. 지난날 놓쳐 버린 것들을 떠올리며 후회하고 앞으로 어떻게 살아야 하는지 방황한다. 나 아닌 다른 것으로 채워진 삶에 공허와 권태를 느끼면서 무언가를 좇으며 도리어 분노하고 두려워한다. 지금 가진 것들을 잃을지도 모른다는 생각에 우울하고 슬프다. 마흔의 당신에게 니체가 인생의 마지막 질문을 던진다. “나는 어떻게 이 삶을 사랑할 것인가?”\n\n인생에 전환점이 필요할 때, 더 나은 방향으로 나아가고자 할 때, 내 삶을 제대로 사랑하고 싶을 때, 죽기 전에 한 번은 니체를 만나라. 그럼 인생길이 달라질 것이다....",
      "priceSales": 14400,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/8\/9\/1\/1\/355138911h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/8\/9\/1\/1\/355138911s.jpg",
      "categoryId": "119",
      "categoryName": "국내도서",
      "publisher": "유노북스",
      "author": "장재형",
      "isbn": "9791192300245",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355138911&amp;refererType=8305",
      "rank": 15
     },
     {
      "itemId": 355752911,
      "title": "우리, 편하게 말해요",
      "description": "“아무도 말하는 법을 제대로 알려준 적이 없잖아요.이제 같이 해요.”18년 동안 3만 여명의 사람들과일과 사랑, 인생을 이야기한‘레전드 방송인’아나운서 이금희가 33년의 내공을 담아말하기의 태도와 기술을 전하다“말하기가 낯설고 서투른 이들에게 용기를 선물해주는 책.”_한지민, 배우“적절하고 유창한 언어를 구사하게 도움을 주는 가이드인 동시에누군가에게는 삶의 기준이 되어줄 것이다.”_박상영, 소설가“방송을 주재하면서도 결코 스스로를 전면에 내세우지 않고, 그러면서도 부드러운 진행으로 누군가가 다른 누군가를 파묻어버리지 않게 하는 특별한 매력을 지녔다.” 말하기를 테크닉이 아니라 태도로 접근하는 독보적인 진행자, 대한민국에서 가장 공들여서 말하기를 해온 사람. 모든 이들이 이금희 앞에서는 자신의 이야기를 술술 ...",
      "priceSales": 15300,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/2\/9\/1\/1\/355752911h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/2\/9\/1\/1\/355752911s.jpg",
      "categoryId": "118",
      "categoryName": "국내도서",
      "publisher": "웅진지식하우스",
      "author": "이금희,이금희",
      "isbn": "9788901264776",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355752911&amp;refererType=8305",
      "rank": 16
     },
     {
      "itemId": 355855371,
      "title": "창발의 시대",
      "description": "이 책은 현대 세계가 어떻게 형성되었는지 그 흥미로운 역사로 안내하는경제적, 문화적 격변의 그랜드 투어라 할 수 있다. 박식하면서 매력적인 책이다.재커리 D. 카터, 《존 메이너드 케인스》 저자16세기 이전까지 동양보다 낙후되었던 서양은 어떻게 잘살게 되었는가?경제, 사회, 문화, 정치, 기술 등 광범위한 영역에서 연결과 창발이 일어났기 때문이다!현대 세계와 우리의 일상이 어떻게 형성되었는지 알고 싶다면 꼭 읽어야 할 책! 우리가 사는 현재를 이해하려면 과거를 알아야 한다. 그래서 우리는 역사를 공부하고 그 속에서 오늘날 우리에게 도움이 되는 교훈을 얻는다. 역사학 박사이자 인기 있는 역사 팟캐스트 시리즈 ‘역사의 조류(Tides of History)’를 제작하는 패트릭 와이먼은 이 책에서 서양과 세계 역사...",
      "priceSales": 17550,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/5\/3\/7\/1\/355855371h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/5\/3\/7\/1\/355855371s.jpg",
      "categoryId": "117",
      "categoryName": "국내도서",
      "publisher": "커넥팅",
      "author": "패트릭 와이먼,패트릭 와이먼",
      "isbn": "9791140802586",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355855371&amp;refererType=8305",
      "rank": 17
     },
     {
      "itemId": 355929774,
      "title": "흔한남매 과학 탐험대 6: 물리 2",
      "description": "카이스트 과학영재교육연구원 연구진 기획 및 감수흔한남매와 떠나는 흥미진진 과학 대모험교과서를 통째로 넣은 초등 과학 입문서의 결정판!냐하~! 요절복통 장난꾸러기 흔한남매와 함께하는 과학 첫걸음.《흔한남매 과학 탐험대》 시리즈는 과학을 처음 접하는 아이들이 과학의 주요 내용을 미리 맛볼 수 있는 초등 과학 입문서이다. 흔한남매가 최고의 과학 전문가들과 함께 우주, 지구와 달, 우리 몸, 정글 등을 여행하며 쉽고 재미있게 과학 지식을 배운다. 초등학교 과학 교과서의 내용을 모두 담았고, 생활 과학 정보, 과학 관련 최근 이슈, 우리나라 관련 정보들을 더했다. 흔한남매와 함께라면 학교에서 처음 배우는 과학이 두렵지 않다!놀이공원 탐험에 이어 이번엔 가상 현실 게임을 즐기며 물리 법칙을 알아본다. 친절한 게임방 누...",
      "priceSales": 12600,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/9\/7\/7\/4\/355929774h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/9\/7\/7\/4\/355929774s.jpg",
      "categoryId": "110",
      "categoryName": "국내도서",
      "publisher": "주니어김영사",
      "author": "정현철,이현진,흔한남매,닥터 스코(권태균)",
      "isbn": "9788934946793",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355929774&amp;refererType=8305",
      "rank": 18
     },
     {
      "itemId": 355777340,
      "title": "주식과 비교하면 더 쉽게 이해되는 아파트 투자는 사이클이다",
      "description": "대한민국 부동산 시장을 소름 끼치도록 정확히 예측한 진짜 전문가전세계 투자 대가의 격언을 빌려 아파트 사이클과 매매 타이밍을 설명한다!아파트사이클연구소 이현철 소장은 여러 부동산 전문가가 하락을 점치던 2018~2019년에 ‘부동산 폭등장이 온다!’고 외치고, 모두가 한목소리로 집은 오늘이 가장 싸니까 무조건 사야 한다고 부르짖던 2021년에는 조정을 지나 본격적인 하락장이 도래할 것이라며 매도를 권유했다. 또한 임대차 3법 시행 만 2년이 되는 2022년 8월 전세대란이 올 거라는 부동산 전문가들의 한결같은 예측과 반대로 ‘8월 전세대란은 없다!’며 못을 박았다. 전문가들이 자신의 빗나간 전망에 대한 해명 없이 달라진 시장에 따라 입장을 바꿀 때, 이현철 소장의 전망은 현실에서 그대로 실현되고 있다. 예언...",
      "priceSales": 18000,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/7\/3\/4\/0\/355777340h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/7\/3\/4\/0\/355777340s.jpg",
      "categoryId": "117",
      "categoryName": "국내도서",
      "publisher": "여의도책방",
      "author": "이현철,이현철",
      "isbn": "9791191904048",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355777340&amp;refererType=8305",
      "rank": 19
     },
     {
      "itemId": 355854916,
      "title": "타인의 마음",
      "description": "인지심리학자 김경일과지식 큐레이팅 유튜브 채널 〈사피엔스 스튜디오〉의‘타인의 심리 읽어드립니다’ 출간!입만 열면 남과 비교하는 사람,SNS는 하면서 내 연락에는 답이 없는 사람,자기 말만 다 맞는다는 사람,쉴 새 없이 남 욕을 하는 사람 등……이해할 수 없는 말과 행동으로 나를 힘들게 만드는불편한 타인들의 심리를 탐구하다!인간의 심리를 가장 쉽고 명쾌하게 전달하는 인지심리학자 김경일과 tvN 〈책 읽어드립니다〉 〈어쩌다 어른〉의 제작팀이 만든 CJ ENM 디지털 지식 플랫폼 〈사피엔스 스튜디오〉가 만나 제작한 ‘타인의 심리 읽어드립니다’가 책으로 출간되었다.《타인의 마음》은 구독자 165만 명을 보유한 지식 큐레이팅 유튜브 채널 〈사피엔스 스튜디오〉의 인기 콘텐츠인 ‘타인의 심리 읽어드립니다’(조회수 누적 ...",
      "priceSales": 16200,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/4\/9\/1\/6\/355854916h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/4\/9\/1\/6\/355854916s.jpg",
      "categoryId": "119",
      "categoryName": "국내도서",
      "publisher": "샘터(샘터사)",
      "author": "김경일,사피엔스 스튜디오",
      "isbn": "9788946422278",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355854916&amp;refererType=8305",
      "rank": 20
     },
     {
      "itemId": 355979168,
      "title": "그리스 로마 신화 31: 아이네이아스의 새로운 여정",
      "description": "그리스 로마 신화의 이야기를 재미있는 만화로 풀어내고 신화 속 지식을 쉽게 구성한 책이다. 그리스 로마 신화는 서양의 문화를 이해하는 원천이고, 신과 영웅들의 다양한 모습을 통해 삶의 지혜를 배울 수 있는 인류 최고의 고전이다. 또한 수천 년 동안 무한히 펼쳐진 상상력의 세계를 담고 있기도 하다. 이처럼 중요한 고전이지만 신화를 읽는 어린이들은 복잡하고 어렵게 느껴져 읽기 쉽지 않았다.은 아이네이아스부터 로물루스, 이름난 여러 황제들로 이어지는 로마의 신화와 역사를 재미난 이야기 형식으로 꾸몄다. 신화에 대한 쉽고 재미난 해석으로 어린이들이 신화에 친근감을 느끼고, 신화와 역사를 제대로 이해하는 데 큰 도움을 준다.",
      "priceSales": 13500,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/9\/1\/6\/8\/355979168h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/9\/1\/6\/8\/355979168s.jpg",
      "categoryId": "110",
      "categoryName": "국내도서",
      "publisher": "아울북",
      "author": "박시연",
      "isbn": "9788950941567",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355979168&amp;refererType=8305",
      "rank": 21
     },
     {
      "itemId": 355939290,
      "title": "이상한 과자 가게 전천당 16",
      "description": "《이상한 과자 가게 전천당 16권》에서는 베니코가 가짜 베니코를 찾아다니며 연구소를 조사하기 시작한다. 불량 과자 때문에 머릿니가 득실거려 낭패를 봤던 신타에게 가짜 베니코의 특징과 가는 곳 등을 묻는다. 피해를 봤던 또 다른 사람들을 차례씩 찾아다니며 가짜 베니코와 로쿠조를 잡는 일에 바짝 다가선다. 그 사이 가짜 베니코와 로쿠조는 모략을 꾸며 전천당의 평판을 떨어뜨리려는 짓을 계속하고 다닌다.베니코는 예전에 로쿠조 연구소에서 근무했던 세키노세의 도움으로 연구소의 핵심 시설에 들어가게 된다. 로쿠조와의 거리가 서서히 좁혀지면서 둘 사이의 긴장감이 치솟는다. 비상한 두뇌를 복수심에 철저히 사용했던 로쿠조의 놀라운 사연이 드러나고, 로쿠조와 전천당 가게 사이에 얽히고설킨 악연이 밝혀진다.",
      "priceSales": 11700,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/9\/2\/9\/0\/355939290h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/9\/2\/9\/0\/355939290s.jpg",
      "categoryId": "110",
      "categoryName": "국내도서",
      "publisher": "길벗스쿨",
      "author": "히로시마 레이코(廣嶋 玲子)",
      "isbn": "9791164064748",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355939290&amp;refererType=8305",
      "rank": 22
     },
     {
      "itemId": 355590243,
      "title": "명화로 읽는 합스부르크 역사",
      "description": "★역사가 흐르는 미술관 시리즈 일본 누계 35만 부 판매!★\n\n기요틴의 이슬이 된 마리 앙투아네트, 미남왕 펠리페, 비극적 황후 엘리자베트…\n합스부르크가를 알면 유럽사가 보인다!\n\n《무서운 그림》의 저자 나카노 교코가 명화를 통해 유럽 왕조의 역사를 들려주는 \n‘역사가 흐르는 미술관’ 시리즈 첫 번째 책 \n《명화로 읽는 합스부르크 역사》 출간\n\n시대를 대표하는 명화를 통해 배우는\n역사와 인간이 직조하는 화려하고도 피로 물든 세계 \n유럽을 호령한 합스부르크가 650년사\n\n《무서운 그림》 시리즈로 유명한 나카노 교코가 ‘역사가 흐르는 미술관’ 시리즈로 돌아왔다. 명화를 통해 유럽 왕조의 역사를 소개해줄 역사가 흐르는 미술관 시리즈는 총 5권으로 《명화로 읽는 합스부르크 역사》, 《명화로 읽는 부르봉 역사》, 《...",
      "priceSales": 14400,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/0\/2\/4\/3\/355590243h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/0\/2\/4\/3\/355590243s.jpg",
      "categoryId": "105",
      "categoryName": "국내도서",
      "publisher": "한경arte",
      "author": "나카노 교코",
      "isbn": "9788947548472",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355590243&amp;refererType=8305",
      "rank": 23
     },
     {
      "itemId": 355900858,
      "title": "머니 트렌드 2023",
      "description": "대한민국 최고의 경제 전문가들이 한자리에 모여 미래를 예측하다한국 경제의 주식, 부동산, 사회 문제, 인구, 테크 등분야별 돈의 흐름 예측과 부자 되는 전략 45가지!한발 앞설 것인가, 한발 뒤처질 것인가? 부의 대변동이 일어날 2023년 계묘년, 돈의 흐름을 붙잡고 싶다면 반드시 알아야 할 45가지 머니 트렌드 끝을 모르고 곤두박질치는 경제 상황 속에서 2023년을 어떻게 맞이하느냐가 우리의 미래 자산을 좌우할 것이다. 보유 자산을 최대한 지키면서 부를 더 불려가고 싶은 이들을 위해 반드시 알고 대비해야 할 45가지 핵심 머니 트렌드를 한 권의 책으로 탄생시켰다. 부동산, 주식, 메타버스, 인구, 재테크 등 다양한 분야의 전문가들이 힘을 합쳐 돈의 흐름을 전망하고, 부자가 될 수 있는 크고 작은 노하우와 ...",
      "priceSales": 17100,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/0\/8\/5\/8\/355900858h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/0\/8\/5\/8\/355900858s.jpg",
      "categoryId": "117",
      "categoryName": "국내도서",
      "publisher": "사용안함",
      "author": "장태익,전영수,김상균,김경민,김도윤",
      "isbn": "9791191891232",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355900858&amp;refererType=8305",
      "rank": 24
     },
     {
      "itemId": 355397440,
      "title": "참 괜찮은 태도",
      "description": "“어떤 순간에도 사람을 수단으로 대하지 말기를…”\n15년간 KBS ‘다큐멘터리 3일’, tvN ‘유 퀴즈 온 더 블럭’의 \n다큐멘터리 디렉터로 일해 온 저자가 수많은 사람들의 삶에서 길어 올린 인생의 말들\n\nKBS ‘다큐멘터리 3일’, tvN ‘유 퀴즈 온 더 블럭’의 다큐멘터리 디렉터로 일해 온 저자가 길 위에서 만난 수많은 사람들에게 배운 삶의 의미와 단단한 인생의 태도들을 정리한 책이다. 저자는 15년 넘게 카메라를 들고 국내외 곳곳을 누비면서 노숙자부터 대통령까지 안 만나 본 사람이 없을 정도로 길 위에서 수많은 사람들을 만났다. 그리고 그들의 진솔한 이야기를 들으며 삶의 해답을 찾고 그들에게서 따뜻한 위로와 삶의 지혜를 얻어 왔다. 덕분에 저자는 자신이 얼마나 좁은 세상에서 수많은 오해와 편견에 사...",
      "priceSales": 15120,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/7\/4\/4\/0\/355397440h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/7\/4\/4\/0\/355397440s.jpg",
      "categoryId": "119",
      "categoryName": "국내도서",
      "publisher": "메이븐",
      "author": "박지현",
      "isbn": "9791190538480",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355397440&amp;refererType=8305",
      "rank": 25
     },
     {
      "itemId": 355506023,
      "title": "작은 땅의 야수들",
      "description": "마침내 우리가 기다려온 가장 한국적이고 가장 세계적인 이야기!\n『파친코』를 잇는 한국적 서사의 새로운 주역\n한국계 미국인 작가 김주혜의 놀라운 데뷔작\n \n“먼 나라에서 도래한 우리 이야기, 새로운 정통의 출현을 알리는 신호탄!\n이것은 하나의 거스를 수 없는 흐름, 크고 거센 흐름이다.”\n_소설가 박서련(한겨레문학상 수상작 『체공녀 강주룡』 저자)",
      "priceSales": 16200,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/6\/0\/2\/3\/355506023h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/6\/0\/2\/3\/355506023s.jpg",
      "categoryId": "101",
      "categoryName": "국내도서",
      "publisher": "다산책방",
      "author": "김주혜",
      "isbn": "9791130693927",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355506023&amp;refererType=8305",
      "rank": 26
     },
     {
      "itemId": 355124215,
      "title": "파친코 2",
      "description": "“역사는 우리를 저버렸지만, 그래도 상관없다”\n역사에 외면당한 재일조선인 가족의 대서사극\n전 세계를 감동시킨 이민진 작가 화제작 《파친코》 새롭게 출간!\n\n“내게 ‘한국인’은 이야기의 주인공이 될 가치가 있는 이들이다.\n나는 가능한 한 오래 한국인 이야기를 쓰고 싶다.” \n- ‘한국 독자들에게’ 중에서\n\n4대에 걸친 재일조선인 가족의 이야기를 그린 세계적 베스트셀러, 이민진 작가의 장편소설 《파친코》가 새롭게 출간되었다. 《파친코》는 재미교포 1.5세대인 이민진 작가가 30년에 달하는 세월에 걸쳐 집필한 대하소설로, 2017년 출간되어 《뉴욕타임스》 베스트셀러에 올랐다. 현재까지 전 세계 33개국에 번역 수출되었으며, BBC, 아마존 등 75개 이상의 주요 매체의 ‘올해의 책’으로 선정되었을 뿐 아니라 전미...",
      "priceSales": 14220,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/4\/2\/1\/5\/355124215h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/4\/2\/1\/5\/355124215s.jpg",
      "categoryId": "101",
      "categoryName": "국내도서",
      "publisher": "인플루엔셜",
      "author": "이민진",
      "isbn": "9791168340541",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355124215&amp;refererType=8305",
      "rank": 27
     },
     {
      "itemId": 355777359,
      "title": "조셉 머피 부의 초월자",
      "description": "“책이 찢어질 정도로매일 읽고 또 읽었다!”60년간 읽혀 온 1% 부자들의 베스트셀러!‘잠재의식의 아버지’ ‘성공학의 대가’ ‘부의 인도자’조셉 머피가 드디어 돌아왔다!★★★ 전 세계 17개국 번역, 시리즈 누계 수백만 부 판매! ★★★★★★ 60년간 읽혀 온 역사상 가장 뛰어난 자기계발서 시리즈 ★★★★★★ 조셉 머피 재단이 인정한 유일한 공식 시리즈의 국내 최초 완역본! ★★★★★★ 실제 사례로 증명된 ‘부의 확언’ 73개 수록! ★★★‘잠재의식의 아버지’라고 불리며 잠재의식을 활용한 다양한 기법의 선구자로 평가되고, 20세기 중반에 가장 많이 팔린 작가 중 한 명으로서 ‘성공학의 대가’로 인정받는 조셉 머피 박사! 조셉 머피 박사는 신학을 비롯해 아시아의 종교와 동양 철학, 법학, 의학 등을 바탕으로 ...",
      "priceSales": 19800,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/7\/3\/5\/9\/355777359h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/7\/3\/5\/9\/355777359s.jpg",
      "categoryId": "118",
      "categoryName": "국내도서",
      "publisher": "다산북스",
      "author": "조셉 머피,조셉 머피",
      "isbn": "9791130693989",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355777359&amp;refererType=8305",
      "rank": 28
     },
     {
      "itemId": 355882190,
      "title": "주택청약의 모든 것",
      "description": "청약, 기초가 튼튼해야실패하지 않는다전 국민이 청약을 통한 내 집 마련의 관심으로 뜨겁습니다. 청약 정보를 제공하는 콘텐츠도 연일 앞다투어 쏟아져 나옵니다. 그러나 애석하게도, 청약에 비법이나 지름길은 없습니다. 청약은 법에서 정한 방식에 따라 당첨자를 선정합니다. 운이 작용하는 단순 추첨 방식이 아니라 반드시 소득 유형, 순위, 거주 지역 등 우선순위에 따라 당락이 결정됩니다.게다가 ‘당첨부터 되고 보자’라는 식의 생각은 경계해야 합니다. 청약은 당첨으로 끝나는 것이 아닙니다. 부적격 당첨자가 되지 않고 무사히 분양계약 후 대금납부 그리고 입주까지 해야 내 집 마련의 대장정이 마무리되기 때문입니다.청약에 대해 올바로 이해하고 있다면 자신이 어떤 유형의 청약 신청을 준비해야 하는지 알아야 합니다. 청약제도는...",
      "priceSales": 10800,
      "coverSmallUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/2\/1\/9\/0\/355882190h.jpg",
      "coverLargeUrl": "https:\/\/bimage.interpark.com\/partner\/goods_image\/2\/1\/9\/0\/355882190s.jpg",
      "categoryId": "117",
      "categoryName": "국내도서",
      "publisher": "한빛비즈",
      "author": "한국부동산원,한국부동산원",
      "isbn": "9791157846276",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355882190&amp;refererType=8305",
      "rank": 29
     },
     {
      "itemId": 355778158,
      "title": "나의 문화유산답사기 11: 서울편(3)",
      "description": "서울의 어제와 오늘을 거쳐\n‘답사기’ 서울편 드디어 완간!\n\n초대형 베스트셀러이자 한국 인문서를 대표하는 시리즈 『나의 문화유산답사기』가 서울편 완간 소식을 가지고 돌아왔다. 시리즈 중에서도 큰 사랑을 받았던 서울편 1~2권 출간 이후 중국편 3권을 거쳐 5년 만에 서울편 3~4권으로 찾아온 것이다. 이번에 출간되는 서울편 3권 ‘사대문 안동네: 내 고향 서울 이야기’와 4권 ‘강북과 강남: 한양도성 밖 역사의 체취’는 세계인이 사랑하는 도시 서울의 오래된 동네와 뜻깊은 문화유산을 탐방하고 그곳의 매력적인 이력을 풀어내며 서울편 대장정을 마무리한다.\n\n수도 600년의 오랜 세월 동안 서울은 점차 넓어지고 깊어져왔다. 저자는 지난 1~2권에 이어서 대도시 서울의 어제와 오늘을 섬세하게 통찰하는 한편, 지금까지...",
      "priceSales": 19800,
      "coverSmallUrl": "http:\/\/bimage.interpark.com\/goods_image\/8\/1\/5\/8\/355778158h.jpg",
      "coverLargeUrl": "http:\/\/bimage.interpark.com\/goods_image\/8\/1\/5\/8\/355778158s.jpg",
      "categoryId": "128",
      "categoryName": "국내도서",
      "publisher": "창비",
      "author": "유홍준(兪弘濬)",
      "isbn": "9788936479190",
      "link": "http:\/\/book.interpark.com\/blog\/integration\/product\/itemDetail.rdo?prdNo=355778158&amp;refererType=8305",
      "rank": 30
     }
    ]
}}